config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :books
  resources :homes
  resources :users
  resources :about
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :book, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def about
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_path(@book)
  end

  def index
    @book = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
  end

  def about
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 def top
 end
 def new
 end

 def create
 end

 def index
 end

 def show
 end

 def destroy
 end

 def about
 end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
  end

  def edit
    @users = User.find(params[:id])
  end

  def update
    @users = User.find(params[:id])
    @users.update(users_params)
    redirect_to user_path(@users)
  end

  def about
  end

  private

  def users_params
    params.require(:user).permit(:name, :image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
  <main>
    <p>
    </p>
    <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <img class="attachment user profile_image fallback" src="/">
      <table class="table">
  <tbody>
    <tr>
    </tr>
  <tr>
	  <th>
	    name
	  </th>
	  <th>
	  </th>
  </tr>
  <tr>
	  <th>
	    introduction
	  </th>
	  <th>
	  </th>
  </tr>
</tbody>
</table>

<div class="row">
  <a class="btn btn-outline-secondary btn-block fas fa-user-cog edit_user_16008" href="/users/edit">
  </a>
</div>
 <form action="/books" accept-charset="UTF-8" method="post">
   <input name="utf8" type="hidden" value="">
   <input type="hidden" name="authenticity_token" value="">
  <div class="form-group">
    <label for="book_title">
      Title
    </label>
    <input class="form-control book_title" type="text" name="book[title]" id="book_title">
  </div>
  <div class="form-group">
    <label for="book_opinion">
      Opinion
    </label>
    <textarea class="form-control book_body" name="book[body]" id="book_body">
    </textarea>
  </div>
  <div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>
  <div class="col-md-8 offset-md-1">
  <h2>
    Books
  </h2>
  <table class="book_title">
  <thead>
    <tr>
      <th>
      </th>
      <th>
        Title
      </th>
      <th>
        body
      </th>
      <th colspan="3">
      </th>
    </tr>
  </thead>
  <tbody>
  </tbody>
 </table>
    </div>
  </div>
 </div>
</main>
<footer>
  <div class="copy">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
</html>

app/views/books/show.html.erb
<head>
    <link rel="stylesheet" href="books.scss" />
    <title>bookersver2</title>
</head>
<main>
    <p>
    </p>
    <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <img class="attachment user profile_image fallback" src="/">
      <table class="table">
  <tbody>
    <tr>
    </tr>
  <tr>
	  <th>
	    name
	  </th>
	  <th>

	  </th>
  </tr>
  <tr>
	  <th>
	    introduction
	  </th>
	  <th>

	  </th>
  </tr>
</tbody>
</table>

<div class="row">
  <a class="btn btn-outline-secondary btn-block fas fa-user-cog edit_user_16008" href="/users/edit">
  </a>
</div>
 <form action="/books" accept-charset="UTF-8" method="post">
   <input name="utf8" type="hidden" value="">
   <input type="hidden" name="authenticity_token" value="">
  <div class="form-group">
    <label for="book_title">
      Title
    </label>
    <input class="form-control book_title" type="text" name="book[title]" id="book_title">
  </div>
  <div class="form-group">
    <label for="book_opinion">
      Opinion
    </label>
    <textarea class="form-control book_body" name="book[body]" id="book_body">
    </textarea>
  </div>
  <div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>
  <div class="col-md-8 offset-md-1">
  <h2>
    Books
  </h2>
  <table class="book_title">
  <thead>
    <tr>
      <th>
      </th>
      <th>
        Title
      </th>
      <th>
        body
      </th>
      <th colspan="3">
      </th>
    </tr>
  </thead>
  <tbody>
  </tbody>
 </table>
    </div>
  </div>
 </div>
</main>
<footer>
  <div class="copy">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/homes/about.html.erb
<main>
 <p id="notice">
 </p>
  <div class="container">
   <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book">
     </i>
      <strong>
       Bookers
      </strong>!
     </h1>
   </div>
 </div>
</main>

app/views/homes/top.html.erb
<head>
     <link rel="stylesheet" href="homes.scss">
    <script src="https://kit.fontawesome.com/34c9407723.js" crossorigin="anonymous">
    </script>
</head>
<main>
  <p class="are">
  </p>
  <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to
      <i class="fas fa-book">
      </i>
      <strong>
          Bookers
      </strong>
      !!
      </h1>
      <p>
          In
      <i class="fas fa-book">
      </i>
      <strong>
          Bookers
      </strong>
      ,
      </p>
      <p>
          you can share and exchange  your opinions , inpressions , and emotions
      </p>
      <p>
          about various books!
      </p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/34c9407723.js" crossorigin="anonymous"></script>
  </head>

  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>
          Bookers
        </span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
        </span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li>
           <i class="fas fa-home">
            <%= link_to "Home", root_path %>
           </i>
          </li>
           <% if user_signed_in? %>
           <li>
             <i class="fas fa-sign-out-alt">
              <%= link_to "logout" , destroy_user_session_path, method: :delete %>
             </i>
           </li>
           <li>
             <i class="fas fa-users">
              <%= link_to "Users", user_session_path  %>
             </i>
           </li>
           <li>
             <i class="fas fa-book-open">
              <%= link_to "Books", books_path %>
             </i>
           </li>
           <% else %>
          <li>
            <i class="fas fa-link">
             <%= link_to "About", books_path %>
            </i>
          </li>
          <li>
            <i class="fas fa-user-plus">
             <%= link_to "signup", new_user_registration_path %>
            </i>
          </li>
          <li>
            <i class="fas fa-sign-in-alt">
             <%= link_to "login", new_user_session_path %>
            </i>
          </li>
           <% end %>
        </ul>
      </div>
    </div>
  </nav>
  </header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
  <main class="user">
    <p>
    </p>
    <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <img class="attachment user profile_image fallback" src="/">
      <table class="table">
  <tbody>
    <tr>
    </tr>
  <tr>
	  <th>
	    name
	  </th>
	  <td>
	    <%= @user.name %>
	  </td>
  </tr>
  <tr>
	  <th>
	    introduction
	  </th>
	  <td>
     <%= @user.introduction %>
	  </td>
  </tr>
</tbody>
</table>

<div class="row">
  <a class="btn btn-outline-secondary btn-block fas fa-user-cog edit_user_16008" href="/users/edit">
  </a>
</div>
 <form action="/books" accept-charset="UTF-8" method="post">
   <input name="utf8" type="hidden" value="">
   <input type="hidden" name="authenticity_token" value="">
  <div class="form-group">
    <label for="book_title">
      Title
    </label>
    <input class="form-control book_title" type="text" name="book[title]" id="book_title">
  </div>
  <div class="form-group">
    <label for="book_opinion">
      Opinion
    </label>
    <textarea class="form-control book_body" name="book[body]" id="book_body">
    </textarea>
  </div>
  <div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>
  <div class="col-md-8 offset-md-1">
  <h2 class="box">
    Books
  </h2>
  <table class="book_title">
  <thead>
    <tr>
      <th>
      </th>
      <td class="box">
        Title
      </td>
      <td class="box">
        body
      </td>
      <th colspan="3">
      </th>
    </tr>
  </thead>
  <tbody>
  </tbody>
 </table>
    </div>
  </div>
 </div>
</main>
<footer>
  <div class="copy">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
</html>